# Generated by Django 4.0.2 on 2022-03-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='Age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='BirthDay',
            field=models.DateField(verbose_name='Birth day'),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='FName',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='LName',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
    ]
