# Generated by Django 4.0.2 on 2022-03-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mytable_age_alter_mytable_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='BirthDay',
            field=models.DateField(verbose_name='Birth Day'),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='FName',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='LName',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
    ]
