# Generated by Django 4.0.2 on 2022-03-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_mytable_birthday_alter_mytable_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytable',
            name='BirthDay',
        ),
    ]
