# Generated by Django 4.0.2 on 2022-03-14 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_mytable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='BirthDay',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth Day'),
            preserve_default=False,
        ),
    ]
